
# Database
# spring.datasource.url=postgres://default:5wdA3vGaFqkr@ep-late-lab-984293-pooler.us-east-1.postgres.vercel-storage.com:5432/verceldb
# spring.datasource.username=default
# spring.datasource.password=5wdA3vGaFqkr
# POSTGRES_URL="postgres://default:5wdA3vGaFqkr@ep-late-lab-984293-pooler.us-east-1.postgres.vercel-storage.com:5432/verceldb"
# POSTGRES_PRISMA_URL="postgres://default:5wdA3vGaFqkr@ep-late-lab-984293-pooler.us-east-1.postgres.vercel-storage.com:5432/verceldb?pgbouncer=true&connect_timeout=15"
# POSTGRES_URL_NON_POOLING="postgres://default:5wdA3vGaFqkr@ep-late-lab-984293.us-east-1.postgres.vercel-storage.com:5432/verceldb"
# POSTGRES_USER="default"
# POSTGRES_HOST="ep-late-lab-984293-pooler.us-east-1.postgres.vercel-storage.com"
# POSTGRES_PASSWORD="5wdA3vGaFqkr"
# POSTGRES_DATABASE="verceldb"